export const NOTIFICATION_KINDS = [
  "CONTENT_NODE_READY",
  "CONTENT_RESOURCE_REQUESTED",
  "CONTENT_RESOURCE_REVIEWED",
  "IDEA_COLLABORATOR_MATCH",
  "WORK_UNIT_ASSIGNED",
  "WORK_STEP_ASSIGNED",
  "WORK_STEP_OVERDUE",
  "SHOOT_BRIEF_DISPATCHED",
  "EDIT_ASSIGNED",
  "BUILD_ASSIGNED"
] as const;
export type NotificationKind = (typeof NOTIFICATION_KINDS)[number];
